### ISSUE TITLE
Correction of misleading statements in README

### ISSUE THREAD

**Issue by dumblob** [gek169/OpenIMGUI_Standard#1]
## Correction of misleading statements in README

Many statements in README seem to be void as [demonstrated throughout the discussion in this thread](https://github.com/Immediate-Mode-UI/Nuklear/issues/272 ) - especially regarding the current state of immediate mode UI libraries/frameworks.

We should correct them and clarify the motivation for this OpenIMGUI standardization initiative.

**Comment by gek169** [comment]
As we discussed in that thread, I have revised my claims against nuklear to better reflect my gripes with it.

Thank you for the report!
~Gek

**Comment by gek169** [comment]
if you have any further issues please feel free to post them here.
